apiVersion: apps/v1
kind: Deployment
metadata:
  name: santhosh
  labels:
    app: nginx
  namespace: asd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: santhoshshelby/mycustomrepo
        ports:
        - containerPort: 80
